/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import { BASE_URL, requestOptions } from './common.js';

const commentswithusersAPI_auto = {

    /** Gets all entries from 'commentswithusers' */
    getAll: async function() {
        let response = await axios.get(`${BASE_URL}/commentswithusers`, requestOptions);
        return response.data;
    },

    /** Gets an array entries from 'commentswithusers' by their commentId.
        Note that this always returns an array. */
    getByCommentId: async function() {
        let response = await axios.get(`${BASE_URL}/commentswithusers?commentId=${commentId}`, requestOptions);
        return response.data;
    },

    /** Gets an array entries from 'commentswithusers' by their userId.
        Note that this always returns an array. */
    getByUserId: async function() {
        let response = await axios.get(`${BASE_URL}/commentswithusers?userId=${userId}`, requestOptions);
        return response.data;
    },

    /** Gets an array entries from 'commentswithusers' by their photoId.
        Note that this always returns an array. */
    getByPhotoId: async function() {
        let response = await axios.get(`${BASE_URL}/commentswithusers?photoId=${photoId}`, requestOptions);
        return response.data;
    },
};

export { commentswithusersAPI_auto };